apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-web-app-test
  namespace: dev-backend
  labels:
    app: golang-web-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-web-app-test
  template:
    metadata:
      labels:
        app: golang-web-app-test
    spec:
      containers:
      - name: golang-web-app
        image: registry.nuha.care/endryco/golang-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_ENV
          value: local
        - name: DB_DRIVER
          value: mysql
        - name: DB_HOST
          value: mysql.database.svc.cluster.local
        - name: DB_PORT
          value: '3306'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: DB_SSL
          value: 'false'
        - name: TZ
          value: Asia/Jakarta
---
apiVersion: v1
kind: Service
metadata:
  name: golang-web-app-test-svc
  namespace: dev-backend
spec:
  type: NodePort
  selector:
    app: golang-web-app-test
  ports:
  - port: 80          # cluster IP service port
    targetPort: 80    # container port
    nodePort: 31513   # akses dari laptop
    protocol: TCP
